### ISSUE TITLE
namespace and class problem

### ISSUE THREAD

**Issue by amanchahal** [chronon/CakePHP-StripeComponent-Plugin#18]
Hi,

I have used your component I do't know if the error is with the new library or what.

1) I have tried number of ways to include the plugin, Every time it gives library not found, Finally when I remove namespace from Stripe.php line then it works good.

2) When I tried to use the library finaly it gives me error that "Stripe_Charge" class not found.

Let me know if it's me or someone else is having same issue.

Regards,

**Comment by chronon** [comment]
Hi,

It must be an issue with how you have the plugin installed or in your app itself as it works for me (and many others). 

Good luck.
