### ISSUE TITLE
Stripe API library is missing or could not be loaded.

### ISSUE THREAD

**Issue by sujeshkumaruv** [chronon/CakePHP-StripeComponent-Plugin#23]
I have placed the files as required in APP/Plugin/Stripe and PHP Stripe Library in APP/Plugin/Stripe/Vendor/Stripe/. The Stripe.php is in lib inside APP/Plugin/Stripe/Vendor/Stripe but I get the error
"Stripe API library is missing or could not be loaded."

**Comment by chronon** [comment]
Did you `git clone --recursive`? Otherwise, I highly suggest installing the plugin with composer.

**Comment by sujeshkumaruv** [comment]
I used git. Has the git method have some issues?

**Comment by sujeshkumaruv** [comment]
<?php

namespace Stripe;

class Stripe
{
    // @var string The Stripe API key to be used for requests.
    public static $apiKey;

    // @var string The base URL for the Stripe API.
    public static $apiBase = 'https://api.stripe.com';

    // @var string The base URL for the Stripe API uploads endpoint.
    public static $apiUploadBase = 'https://uploads.stripe.com';

    // @var string|null The version of the Stripe API to use for requests.
    public static $apiVersion = null;

    // @var boolean Defaults to true.
    public static $verifySslCerts = true;

    const VERSION = '3.3.0';

    /**
     * @return string The API key used for requests.
     */
    public static function getApiKey()
    {
        return self::$apiKey;
    }

    /**
     * Sets the API key to be used for requests.
     *
     * @param string $apiKey
     */
    public static function setApiKey($apiKey)
    {
        self::$apiKey = $apiKey;
    }

    /**
     * @return string The API version used for requests. null if we're using the
     *    latest version.
     */
    public static function getApiVersion()
    {
        return self::$apiVersion;
    }

    /**
     * @param string $apiVersion The API version to use for requests.
     */
    public static function setApiVersion($apiVersion)
    {
        self::$apiVersion = $apiVersion;
    }

    /**
     * @return boolean
     */
    public static function getVerifySslCerts()
    {
        return self::$verifySslCerts;
    }

    /**
     * @param boolean $verify
     */
    public static function setVerifySslCerts($verify)
    {
        self::$verifySslCerts = $verify;
    }
}
This is the Stripe.php file in lib folder. No idea why after import the !class_exists function shows error.

**Comment by chronon** [comment]
You're not installing the things right since you ended up with version 3.3.0 of the Stripe PHP library. [Per this issue](https://github.com/chronon/CakePHP-StripeComponent-Plugin/issues/19) this plugin supports up to version 1.18.x. As I mentioned above, if you `git clone --recursive` it should pull in the correct Stripe library.

**Comment by sujeshkumaruv** [comment]
Thanks.
Did not scroll through all issues. 
Do mention it in the description if possible. 
Thanks again.

**Comment by sujeshkumaruv** [comment]
I have started using it with 3.3.0 with certain tweaks. Let see how it works.
