### ISSUE TITLE
Add log to record the transcations

### ISSUE THREAD

**Issue by mingxing** [chronon/CakePHP-StripeComponent-Plugin#27]
Hi guys

Great job! I would like to see whether we can add a log or event listener to record the transactions, just like another plugin: Plugin/PaypalIpn/Controller/InstantPaymentNotificationsController.php

Listens for Saved Events in this function public function afterPaypalNotification($txnId)

Best Regards
Simon

**Comment by mingxing** [comment]
Perhaps the log config is a solution:

‘’‘<?php
CakeLog::config('stripe', array(
    'engine' => 'FileLog',
    'types' => array('info', 'error'),
    'scopes' => array('stripe'),
    'file' => 'stripe',
’‘’));

Do you have some suggestion?

Simon

**Comment by chronon** [comment]
At the bottom of the README in the [configuration section](https://github.com/chronon/CakePHP-StripeComponent-Plugin#configuration) there is an example logging config which will enable logging.
