### ISSUE TITLE
How to make refund with api?

### ISSUE THREAD

**Issue by miqo-srapionyan** [chronon/CakePHP-StripeComponent-Plugin#30]
I just trying to do refund, find this in Stripe docs 
$refund = \Stripe\Refund::create([
    'charge' => 'ch_sG9ICouetJhw3NvixjWv',
    'amount' => 1000,
]);
how to do it?

**Comment by chronon** [comment]
This deprecated plugin does not support refunds. You may want to check [Omnipay](https://omnipay.thephpleague.com/) as a replacement.
