### ISSUE TITLE
paymentintent ?

### ISSUE THREAD

**Issue by jviure** [chronon/CakePHP-StripeComponent-Plugin#31]
Hi!! I'm trying to change the 

Stripe_Charge::create($chargeData);

for 

\Stripe\PaymentIntent::create($chargeData);

Without luck.. I added the PaymentIntent lib to Stripe.php:
require(dirname(__FILE__) . '/Stripe/PaymentIntent.php');

BUT all them time I receive this error 

Error: Fatal Error (1): Class 'Stripe\ApiResource' not found in [/var/mnt/www/xxxxx/app/api/app/Plugin/Stripe/Vendor/Stripe/lib/Stripe/PaymentIntent.php, line 56

BUT the ApiResource is included a lines before in Stripe.php... some idea how to fix that? thanks! :)

**Comment by chronon** [comment]
Hi - it looks like you're using the [stripe-php](https://github.com/stripe/stripe-php) library directly instead of this (deprecated) component, so I think your question is in the wrong place. Good luck!
