### ISSUE TITLE
Stripe API Libaray is missing or could not be loaded.

### ISSUE THREAD

**Issue by nadiaks** [chronon/CakePHP-StripeComponent-Plugin#8]
Not exactly sure as to why the plugin keep throwing this error at me. I have the latest stripe api loaded in the Vendors folder. Any help would be great.

**Comment by sujeshkumaruv** [comment]
I have the same issue here. However in my lib directory Under APP/Plugin/Stripe/Vendor/Stripe/lib , I don't find any Stripe directory containing the actual library.

**Comment by spacebiscuit** [comment]
This is inherently buggy, every time I try to install this I get missing API library.

As a coder who has to think and work logically I cannot fathom how this still fails when I copy the file contents and structure from another working installation.

Too frustrating!

**Comment by baneetsharma** [comment]
@spacebiscuit same is happening with me. It always says "Stripe API library is missing or could not be loaded". Don't know what am I missing? @chronon there is some problem in component

**Comment by spacebiscuit** [comment]
@baneetsharma install via Git - that worked for me. Curiously, when installed via Git the directory structure was exactly the same as when I copied the folders in manually, so perhaps a permissions error, either way that worked for me.... good luck!

**Comment by chronon** [comment]
As previously mentioned, **installing by composer** is the recommended method. If installing by git for whatever reason, just follow the instructions in the README:

`git clone --recursive https://github.com/chronon/CakePHP-StripeComponent-Plugin.git Plugin/Stripe`
